### ISSUE TITLE
Vertical Rhythm documentation is unclear or there's a bug with trailer and leader heights

### ISSUE THREAD

**Issue by bradgessler** [Compass/compass#1003]
Per I'm trying to figure out how to control `trailer` and `leader` functions in units of the `$base-line-height` from http://compass-style.org/reference/compass/typography/vertical_rhythm/. The problem I'm running into is that I want to control trailer and leaders in units of the base-font-size (not the adjusted font size)

![Trailer and Leader units](https://img.skitch.com/20120824-dqc1681s6q711eerjyqunw11tt.png)

What I'd expect to achieve the result as displayed in the image is `+trailer(2)`.

I'm incorporating typographic principals from http://webtypography.net/Rhythm_and_Proportion/Vertical_Motion/2.2.2/, specifically:

```
One can also set asymmetrical margins for headings, provided the margins combine to be multiples of the basic line height. For example, a top margin of 1½ lines could be combined with a bottom margin of half a line as follows:
```

So if I specified `trailer(1.5)`, I would achieve that outcome based on a margin of 1½ lines. If I wanted to do this to the example I provided, I'd have to do a lot of math to figure out trailer((1/2)*1.5).

If there's a documentation tweak that I can make, I'm happy to fork, write, and submit a pull request. If I need to implement a new function, I'm also happy to do so. I just want to make sure I'm not barking up the wrong tree.

Thanks!

**Comment by mirisuzanne** [comment]
You need to pass the current font size as an argument to the trailer mixin, so that Compass knows what context it is working in:

``` sass
h1
  +adjust-font-size-to(30px);
  +trailer(1,30px);
```

If you want to get really DRY, create an `$h1-size: 30px;` variable to use everywhere needed. Then you can change it in one place.

This is the `$font-size` argument mentioned in the docs: http://compass-style.org/reference/compass/typography/vertical_rhythm/#mixin-trailer

The docs could certainly get more detail here if you want to submit a patch. All the documentation is handled with comments in-line with the code. Feel free to fork and help out. Thanks!

**Comment by bradgessler** [comment]
Thanks @ericam! The point of confusion on `$font-size` was my dropping `$base-font-size` in there, like `+trailer(1, 18px)` thinking that would make an 18 unit all trailer. Renaming the variable to `$adjusted-font-size` might be a little more clear.

I'll fork and play around. I think some examples would go a long way.

Thanks again.
