### ISSUE TITLE
Drop -ms- prefixes for IE10 features

### ISSUE THREAD

**Issue by paulirish** [Compass/compass#1010]
I think we got most of these already but none of the following need -ms- prefixes..
- Radial Gradients
- Linear Gradients
- Keyframe Animations
- Transitions
- Transforms - 3d only as 2d in IE9 needs prefixes
- `font-feature-settings`

[via](http://www.impressivewebs.com/dropping-ms-vendor-prefixes-ie10/)

**Comment by Ne-Ne** [comment]
I have noticed that the prefix "-ms-" is also missing from background-image. It creates all the prefixes apart from this one.

**Comment by mirisuzanne** [comment]
@Ne-Ne Background-image isn't a prefixed css3 property that I know of. Are you talking about one of the background-image options (size, clip, origin) or the gradient functions? I don't think the -ms prefix is used by any browser in any of those situations. Where they are supported, IE uses the official syntax.

**Comment by luketarplin** [comment]
I have found that for IE 10 (Windows 8) the background does need a prefix of -ms- for gradients to work properly, which is annoying since support has been removed from Compass, border-radius and others still have the -ms prefix though. My work around for the time being was to amend the _images.scss file within the compass library to add support for the -ms prefix back in.

**Comment by mirisuzanne** [comment]
I've never seen any mention anywhere of an `-ms-linear-gradient`, and so we have never included support for it:

[caniuse support table](http://caniuse.com/#search=gradients)

I'm willing to bet that you don't have a prefix problem, you have a syntax problem. IE10 supports the new gradient syntax (`to right` instead of `left`), un-prefixed. We're working on support for that new syntax, and you can see it in the "gradients" branch. That issue is being tracked as #965, where you can also find some temporary workarounds.

**Comment by mirisuzanne** [comment]
Is this resolved by the new caniuse support module in 1.0 (alpha), or is there more that needs to be done?

**Comment by mirisuzanne** [comment]
This should be resolved by the caniuse data.
