### ISSUE TITLE
Problem with compression of special characters

### ISSUE THREAD

**Issue by HansRue** [Compass/compass#1116]
Hello,

I found a problem with the compression mode of compass. When I try to create a compressed .css file with the following id selector `#☃{ -sass- }`. It creates `#Ôÿâ{ -compressed css- }`. I guess that there is an issue with compass utf-8 conversion.
On the top of the main.sass file I use `@charset "utf-8";` and all files are saved in with utf-8 encoding. So it should be able to work with utf-8 characters.
At the moment I replaced the id with "normal" text. I just wanted to let you know.

Thanks for the great work on compass!

Greetings.

**Comment by scottdavis** [comment]
this is a feature of sass
http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#output_style

**Comment by rnaud** [comment]
Hello @scottdavis, the link that you refer to does not talk about escaping of utf-8 characters, could you explain a bit more ? I'm having the same issue here.

**Comment by scottdavis** [comment]
Gona have to bug @chriseppstein about the escaping

**Comment by rnaud** [comment]
Well it's be bugging me for a few months now and I usually did not put UTF-8 characters in my css because of this. But I just understood why.

If you put @charset 'UTF-8'; at the top of your scss file, it will be ignored and overwritten by @charset "US-ASCII";
You have to put : @charset "UTF-8"; with double quotes for it to understand that it is UTF-8 and leave it alone.

Talk about precision :)

**Comment by luanmuniz** [comment]
I'm having the same issue.
`content: '»';` are converting to `content: '┬╗';`

Any clues? =/
