### ISSUE TITLE
Shade / Tint aren't working in 0.13

### ISSUE THREAD

**Issue by fredsterss** [Compass/compass#1122]
They just output 'silver', regardless of input and scale.

**Comment by barraponto** [comment]
Tried it out with compass 0.13.alpha.0 and sass 3.2.4, confirm it doesn't work.

**Comment by scottdavis** [comment]
This is the commit where they were added https://github.com/chriseppstein/compass/commit/4928fe17fc99367d87e0c7503f34f756c536d7e6
@jhilden was the author

**Comment by jhilden** [comment]
That's quite weird.  My first guess would have been that something has changed within Sass since that makes up for 95% of what tint/shade do, but I can confirm that it works with compass `0.12.2` and the most recent version of Sass `3.2.5`.  So it must be in compass.  Any ideas what could have changed to break this: https://github.com/chriseppstein/compass/commit/4928fe17fc99367d87e0c7503f34f756c536d7e6#diff-3 ?

**Comment by mirisuzanne** [comment]
That commit was made on June 4, 2012, a month after 0.13.alpha.0 was released. Tint and Shade don't exist in any gem release - only in the master branch.

**Comment by scottdavis** [comment]
Well then that would be why!

**Comment by chriseppstein** [comment]
released now
