### ISSUE TITLE
Prefix -ms-* is needed for linear-gradient

### ISSUE THREAD

**Issue by r007** [Compass/compass#1211]
IE v.10.0.9200:

![ Before adding](https://f.cloud.github.com/assets/78280/250933/a044a60c-8b58-11e2-951b-abda061ae0ed.png)

After adding prefix it looks fine:

![ After adding](https://f.cloud.github.com/assets/78280/250947/38d327ae-8b59-11e2-8dc8-ff506834abfe.png)

**Comment by mirisuzanne** [comment]
That's not the correct fix. IE10 supports un-prefixed gradients _using the new syntax_. Rather than adding a prefix to the old syntax, we are adding support for the new one. You can see discussion on #965 and play with it already in the "gradients" branch: https://github.com/chriseppstein/compass/tree/gradients
