### ISSUE TITLE
Recommended way of requiring a local compass extension?

### ISSUE THREAD

**Issue by robwierzbowski** [Compass/compass#1264]
What is the recommended way to require a local compass extension? For example, if I have a file structure like this:

```
| app/
|-- config.rb
| components/
|-- [compass extension]
```

how can I require the full compass extension, including the ruby in `lib/[extension].rb`? I use `add_import_path` for sass files, but this doesn't work for a full compass extension.

**Comment by robwierzbowski** [comment]
Ah, I see that ad-hoc extensions are the answer, but are currently broken. Closing in favor of the actual issue, https://github.com/chriseppstein/compass/issues/1200.

**Comment by cimmanon** [comment]
Ad-hoc extensions work for me (Compass 0.12.2 (Alnilam)), I'm not entirely sure what the referenced issue is about.  I use them for testing my extensions because its faster than rebuilding them every time I make a change.  They don't need to be (or can't be?) required in config.rb, they're just there as if they were.

**Comment by robwierzbowski** [comment]
You're right. Should have tried it before I posted.

Thanks cimmanon.
