### ISSUE TITLE
Some extension creation questions

### ISSUE THREAD

**Issue by lunelson** [Compass/compass#1267]
So I spent the day trying to create a Compass extension with no luck. The official tutorial explains how to arrange templates and stylesheets but doesn't say very much about ruby files SassScript functions (it sort of says where to put them, but not much about how they get hooked up), and it's the latter I'm after. 

A few questions, just concerning of a local extension with custom SassScript, not yet doing a rubygem:
- is the idea that are you supposed to create an /extensions directory in your compass project (same level as config.rb?), and then create extensions by name in there?
- following that, what steps are then required to get custom `.rb` code (assuming its in the /lib subdir of your extension) included in your compass project? If you put a ruby file at /extensions/ext_name/lib/file.rb, do you first load the extension then require the ruby file by name in compass config.rb?
- how important is the structure within the /lib folder. Could an extension rely on just one ruby file there, and not have to use a separate file for the sassscript extensions?
- finally, how would I get pre-processing programs like codekit, mixture, livereload, takana etc. to load extensions?

This kind of turned out as a "call-for-help" post but I started as an "issue" about the documentation, it would really benefit from a walkthrough of some different variants on simple extensions...

**Comment by robwierzbowski** [comment]
1. Yep. Either use `extensions/` in your project root, or specify a custom directory with `extensions_dir: "[your directory]"` in the config.rb. [See the docs on ad-hoc extensions](http://compass-style.org/help/tutorials/extensions/).
2. Add your ruby to `Sass::Script::Functions` in `lib/[your_extension].rb`. 
   If you've installed an extension as a gem you have to require the extension in your config.rb and then import the gem into your stylesheet. When using ad-hoc extensions you can skip the require step.
3. Not sure exactly what you're asking here.
4. If you tell Codekit to use the global versions of Sass and Compass instead of its sandboxed versions, it will be able to use globally installed extensions. Other programs are probably similar. I'm not sure how they manage ad-hoc extensions.

**Comment by lunelson** [comment]
Hey, thanks for those clarifications. So if I understand correctly, with ruby gems or ad-hoc extensions, then I have to import the my_extension.rb in to my stylesheet _as well as_ do the other steps? Totally missed that one in the docs, if that's the case. What's the syntax? Like importing a sass file? Do I include the .rb extension?

Also: what I meant with my third question above was whether it was necessary to put ruby code and sassScript code in to different files. The docs you linked to above seem to imply that sassscript extension code should be in a further nested dir as "sass_extensions.rb" e.g. "extensions/my_extension/lib/my_extension/sass_extensions.rb", and some of the other extensions I've checked out are written that way, but others seem to just pack everything in to one .rb file.

**Comment by robwierzbowski** [comment]
You don't need to import the ruby files separately, just require and import the extension shorthand for a global gem, and only import for an ad-hoc extension. See the installation instructions for these projects:
https://github.com/Team-Sass/jacket#installation
https://github.com/Team-Sass/breakpoint/wiki/Installation#installation
https://github.com/Team-Sass/Singularity/wiki/Installation#installation

I believe you can organize the ruby any way you like, as long as it ends up being used in the `lib/[your_extension].rb` file, since that's what Compass reads.
