### ISSUE TITLE
Basic Sourcemap support

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#1293]
I'd like to ship basic sourcemap support in 0.13 for application stylesheets and then follow up with more extensive support for extensions's stylesheets in a future release.

This issue will track what basic support means and will block the 0.13 release.

See also: #1108 for ideas around full sourcemap support

**Comment by gabrielgodoy-zz** [comment]
Hello, I managed my compass/sass/sourcemaps to work with the following settings:

Installed:
https://gemnasium.com/gems/compass-sourcemaps/versions/0.12.4.sourcemaps.a4836f1

Working with:
- compass 0.12.4.sourcemaps (clavery-sourcemaps)
- sass 3.3.0.alpha.134 (Bleeding Edge)

Hope this helps.

**Comment by chriseppstein** [comment]
@ggodoyoliveira is there a fork here on github that I can use to read the diffs and see what you did?

**Comment by gabrielgodoy-zz** [comment]
It doesn`t seem to work anymore. Now back again to error "ERROR: Cannot load compass."

For now I'll not be working with compass, only sass to generate sourcemaps (sass --sourcemap --watch sass/main.scss:css/main.css)

**Comment by kevinSuttle** [comment]
Has this been remedied to work in Chrome yet? 
https://developers.google.com/chrome-developer-tools/docs/css-preprocessors

**Comment by ghost** [comment]
+1

**Comment by er1z** [comment]
I'm a bit confused which ticket should we regard into this issue.

Of course, +1.

**Comment by RaphaelDDL** [comment]
I actually managed to work with sourcemaps okay using @ggodoyoliveira settings it's been some months already:

![image](https://f.cloud.github.com/assets/1087109/1201607/90c3c04a-2537-11e3-8315-6a6a0109b7a4.png)
- `gem install sass --pre`
- `gem install compass --pre`
- `gem install compass-sourcemaps --pre`
- Using [compass-generic-config](https://github.com/RaphaelDDL/compass-generic-config/blob/master/config.rb)

What I couldn't make it work at all was the sprite generation only regarding `#public_url`, as I said on my [comment @ #1339](https://github.com/chriseppstein/compass/issues/1339#issuecomment-22498329)

But yeah, basic support is okay with `compass-sourcemaps` using compass' watch. The error "ERROR: Cannot load compass." just happens when invoking compass from sass as `sass --compass --watch stylesheet.scss:stylesheet.css`

**Comment by benjy** [comment]
+1 for this.

**Comment by kevinSuttle** [comment]
Bump.

**Comment by Anahkiasen** [comment]
+1 for this

**Comment by tjtate** [comment]
+3.14159265358979323846264338327950288419716939937510.... :)

**Comment by ricky-ru** [comment]
+1 for this

**Comment by chriseppstein** [comment]
It's in compass 1.0.0.alpha.16. Just released. File bugs if you find them!

**Comment by RaphaelDDL** [comment]
@chriseppstein Does the sourcemap calls changed?

Having the options below on config.rb does not generate the .map files, using `Sass 3.3.0.rc.2 (Maptastic Maple)` + `Compass 1.0.0.alpha.16`.

```
enable_sourcemaps = true
sass_options = {:sourcemap => true }
```

I was using like that with `compass-sourcemaps` gem.

**Comment by mgol** [comment]
@RaphaelDDL From changelog:

```
* Compass now supports Sass sourcemaps. Pass the `--sourcemap` option to
  the compile or watch commands or set `sourcemap = true` in your
  compass configuration.
```

**Comment by RaphaelDDL** [comment]
@mzgol I might be blind but I did a search on the repo for 'changelog' before asking that, and the most up-to-date was  `compass / doc-src / content / CHANGELOG.markdown` [which is 0.12.2](https://github.com/chriseppstein/compass/blob/9ee6b422262668e8a7e154d2ac34f350ee331dc0/doc-src/content/CHANGELOG.markdown)

Could you share where this one you mentioned is?

Anyways, thank you very much =)
:+1: 

Edit:
I confirm the sourcemaps are working. Just when using sprites that still bugs. I'll open an issue then.

**Comment by mgol** [comment]
@RaphaelDDL It's here: https://github.com/chriseppstein/compass/blob/master/compass-style.org/content/CHANGELOG.markdown#100alpha16-12052013

I was just monitoring the repo & found this in a diff on a commit.

EDIT: if you saw 0.12.2 it's because you didn't switch from the `stable` branch to `master` before looking.

EDIT: it's easier to find it here: http://beta.compass-style.org/CHANGELOG/

**Comment by RaphaelDDL** [comment]
@mzgol I changed. But seems github's upper search changes it back to the current 'default' one prior to searching. Thank you again for the urls, will bookmark them =)
