### ISSUE TITLE
Ruby callbacks doesn't run while using compass via sass command line

### ISSUE THREAD

**Issue by Subash** [Compass/compass#1298]
I am doing something like this

`sass style.scss style.css --compass`

config.rb

``` ruby

css_dir = 'css/'
sass_dir = 'scss/'

puts 'not saved yet'

on_stylesheet_saved do |file|
    puts 'Saved'
end

```

I get the `not saved yet` message but never get the `Saved` message.
Configuration variables work as intended but the callback function doesn't get fired.

**Comment by scottdavis** [comment]
When using 'sass --compass' I'm not sure the compass compiler is running to fire the callbacks

**Comment by Subash** [comment]
All compass function work as intended just callbacks are not fired. Configurations are also picked by compass compiler.

**Comment by chriseppstein** [comment]
Supporting this would require registering our callbacks with Sass's callbacks when invoked in the sass cli. you should just use the compass compiler for now.

**Comment by Subash** [comment]
Is there any plan to support this ?

**Comment by chriseppstein** [comment]
@sbspk it seems reasonable and doable, it's just not very high priority. I think the change would need to be in Sass itself. See: https://github.com/nex3/sass/blob/stable/lib/sass/exec.rb#L347-L362

To implement this, I think we should probably refactor compass to make a configuration adapter like `Compass.configuration.configure_sass_cli` which would configure the `Sass::Plugin` object and return engine options. And then we could refactor sass to use that new function if it's available in the version of compass that was loaded. Then, in the future we could largely fix sass integration issues by releasing compass instead of sass.

If someone wants to make patches for sass & compass that accomplish this, I would accept them.

**Comment by Subash** [comment]
I have no experience with ruby. I hope someone will come up to fix this.

**Comment by Subash** [comment]
@chriseppstein  Should I open an issue on sass repo ?
