### ISSUE TITLE
Allow to set `$official` argument to false in css3/shared

### ISSUE THREAD

**Issue by dexteryy** [Compass/compass#1299]
The default browser on Samsung's android devices(for example, S3, Note II) "supports" both `-webkit-transform`/`-webkit-transition` and un-prefix `transform`/`transition`, but un-prefix versions are buggy. So we need ability to disable official syntax for css3 mixins.

https://github.com/chriseppstein/compass/blob/stable/frameworks/compass/stylesheets/compass/css3/_shared.scss#L13

**Comment by cimmanon** [comment]
If you look at master, you can actually control this quite easily on a per module basis.

https://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/css3/_transition.scss

All you should need to do is change the _supports_ variable:

``` scss
$transition-support: append($transition-support, not official);
// or
$transition-support: -moz, -webkit, -o, not -ms, not -khtml, not official;
```

**Comment by chriseppstein** [comment]
NOTE: I do not consider the variables like `$transition-support` to be part of our supported API which is why they are marked `@private` and not shown in the docs. In Sass 3.3 we will have maps and then the support matrix will be officially supported.

I am really torn by this issue. I think people will disable the official syntax and break future-friendliness, and yet the web is messy and buggy.

**Comment by cimmanon** [comment]
I doubt there are many cases where authors will need to disable the official syntax for _all_ properties, likely just a few specific ones.  The new Flexbox mixins suppresses non-prefixed properties from the older drafts.

**Comment by chriseppstein** [comment]
The solution @cimmanon gave will work for you, but please note that in a future release you will have to update your stylesheets when we change how we store this information.
