### ISSUE TITLE
Property lookup a la stylus

### ISSUE THREAD

**Issue by leopic** [Compass/compass#1317]
Example taken from Stylus' documentation:

"...reference properties defined without assigning their values to variables..."

.my-element {
   width: 150px
   height: 80px
   margin-left: -(@width / 2)
   margin-top: -(@height / 2)
}

@width and @height will resolve to the current element's width and height

Read more over at http://learnboost.github.io/stylus/docs/variables.html

**Comment by chriseppstein** [comment]
a) This would be a sass issue, not compass.

b) This has been requested several times. We're not going to add this feature because doing it properly can only be done by a browser after computing the cascade and inheritance for the matched element(s). In a precompiler, this is simply a way to avoid extracting variables -- as such it saves little time and is not worth the complexity.

**Comment by leopic** [comment]
Alright, I tried to find issues about it but got little love from Github, thank you Chris.

**Comment by chriseppstein** [comment]
@leopic it may have been discussed primarily on the sass mailing list.
