### ISSUE TITLE
inline-image SVG without base64 encoding?

### ISSUE THREAD

**Issue by rsanchez** [Compass/compass#1320]
Is there a way to use the inline-image function on an SVG file and have it _not_ base64 encode? You can't alter the fill property via CSS of an SVG if it's encoded. It'd be awesome to be able to choose whether the inline image gets encoded.

**Comment by cimmanon** [comment]
Where are you altering the fill of the SVG from?  It is my understanding that you can't modify the properties of an SVG from within the CSS file that references the SVG.  SVGs can use CSS, but it has to be part of the SVG itself.

**Comment by rsanchez** [comment]
Eh, scratch that. I was wrong about being about to style unencoded svg.

**Comment by joeyhoer** [comment]
@rsanchez Your reasoning may have been misguided, but I believe there is validity to this issue, if for no other reason than to provide substantial gains via gzip compression.

We know that base64 encoding adds approx 35% to the size of the raw data. We also know that gzip can optimize by an almost equal amount (on base64 strings). Ignoring the reduction of HTTP requests, we get an approx net gain of 0 with base64 and gzip.

However, XML (thus SVG), in it's raw form, is _extremely_ compressible. So by preserving SVGs as raw XML we have the potential to drastically reduce file size on style sheets with multiple inlined SVGs, and the obvious reduction of HTTP requests.

@chriseppstein I'd definitely like to see this issue reopened, even at a low priority, so that we might continue this discussion.

**Comment by chriseppstein** [comment]
I don't understand what is being requested here.

**Comment by dtipson** [comment]
Basically, svgs should be percent encoded instead of base64, as this will save a lot more space when compressed.  All that needs to be done is use percent encoding instead of base64, like grunticon now does. https://github.com/filamentgroup/grunticon/commit/bea960893c7ab92d663beb86f0aff3450ea77b8e

It's also worth noting, rsanchez, that you can achieve what you want (using variables to modify properties of svgs) if you use dataURI: i.e. url(data:image/svg+xml;charset=US-ASCII,<svg>etc.</svg>).  The svg is just a string in this case, so with a little bit of work, you can use variables in place of the svg sizes or fill colors. Ultimately, you'd still need to have a function that would percent (or base64) encode that string properly at the end of the process, but that's also relatively easy to write (I'm working on exactly this, atm).  Just extend compass to have a method that runs CGI.escape(string.value).gsub("+", "%20") on any given string, and you're off to the races.

**Comment by cimmanon** [comment]
@dtipson How well supported is this (percent encoded vs base64)?  I have an SVG I would love to be able to theme this way so that I don't have to define the colors in 2 different locations (once within Sass, once within the SVG).
