### ISSUE TITLE
config.rb compile, with auto-install

### ISSUE THREAD

**Issue by gamb** [Compass/compass#1452]
When my compass config file contains `require 'something'`, it would be very useful behaviour if I that gem could be installed as part of the compile process.

Particularly for deployment, `compass compile . -c config/compass_prod.rb`. Have I missed a trick, or is the canonical method to create a Gemfile?

**Comment by lolmaus** [comment]
>  is the canonical method to create a Gemfile?

Exactly.

**Comment by gamb** [comment]
Thanks, LOL

**Comment by lolmaus** [comment]
Don't forget to close this ticket once you think that there's no issue with Compass.

For asking for support, consider using StackOverflow.com rather than Compass issue queue. Though it's not a requirement from Compass team, the Sass/Compass community is pretty active on StackOverflow, so you might get quicker and more abundant answers there, without spamming notifications to Compass development participants and watchers.
