### ISSUE TITLE
sometimes watch err in 1.0.0.alpha.12

### ISSUE THREAD

**Issue by ericjvandervelden** [Compass/compass#1466]
Sometimes, when I edit a scss file, I see

$ compass watch
    info sass/style.scss was removed    

But then this works fine:

$ sass --compass -w sass/:stylesheets
    Deleted template detected: sass/style.scss
    New template detected: sass/style.scss
        write stylesheets/style.css
    ....

But sometimes watch works fine.

**Comment by chriseppstein** [comment]
This is very strange. What editor are you using? are you editing files on a local filesystem?

**Comment by chriseppstein** [comment]
I saw this today. I deleted a file and then the watcher stopped responding.

**Comment by chriseppstein** [comment]
I fixed this. Try the latest (`alpha.17+`)

**Comment by lozandier** [comment]
Compass watch ONLY works normally if I use bundle exec w/  Compass, Sass 3.3, & wdm defined in the Gemfile. 

If I merely use `compass watch,` nothing happens. 

`compass watch` only works for me on Windows when I create a `Gemfile` with the following defined and using `bundle exec compass watch` instead of `compass watch`

```
gem 'sass', '~> 3.3.0.rc.2'
gem 'compass', '~>1.0.0.alpha.17'
gem 'wdm'
```

**Operating System: Windows**
