### ISSUE TITLE
The sourcemap file should have the `.css.map` extension, not `.map`

### ISSUE THREAD

**Issue by mgol** [Compass/compass#1480]
The map file generated by latest Compass has a `.map` extension which makes Chrome DevTools not recognize it: http://crbug.com/327700. While this is clearly a Chrome bug, I can imagine some other tools can make similar assumptions.

It would be a trivial change to Compass to change the extension to `.css.map` which would resolve all these problems.

**Comment by RaphaelDDL** [comment]
Maybe it's Mac OSX only issue.
I'm using Windows7 and both Chrome 31.0.1650.63 m (stable) and 33.0.1734.0 (Canary) are showing the mappings even with just `.map` instead of `.css.map` (which in any case, I think should be the correct one).

![image](https://f.cloud.github.com/assets/1087109/1724815/37c2073c-6276-11e3-8b80-76f4ec117869.png)
_screen from stable_

**Comment by chriseppstein** [comment]
fixed in `1.0.0.alpha.17`
