### ISSUE TITLE
Errno:EACCES on Windows when trying to compile identical file (on watch)

### ISSUE THREAD

**Issue by wilkerlucio** [Compass/compass#15]
In command line, when you save a file a Sass file with same content (changing organization or including a new module for example) the Sass gives a EACESS error, if this happens when the watcher is on before the error, the watch keep listening for changes, but if happens when you start to watch, the program exit, to keep it back working you need to delete the generate CSS files.

**Comment by wilkerlucio** [comment]
after some tests, i found the problem is when the Compass try to touch the file (when detect identical content), after comment the line of touch the scripts runs without problems. The solution maybe is to create a touch implementation to deal with this problem.

**Comment by chriseppstein** [comment]
It would be good if there was a patch that fixes this issue on windows that I could then test on unix based systems. I don't have easy access to windows.

**Comment by chriseppstein** [comment]
The ruby implementation is supposed to work on windows. I'd like to have this bug reproduced by others before taking any action. Are you sure you don't have permission or some other issue that's causing the EACCESS error to be able to modify the file.

**Comment by Talljoe** [comment]
The issue is that, per
https://prototype.lighthouseapp.com/projects/8888/tickets/16-permission-denied-building-via-sprockets-on-windows,
File.utime (called by touch) can't be run against a file that's
already open on Windows.  I've created a patch that uses IO.read()
instead of File.new().read() to read in the existing file so that it
gets closed properly.

Patch at http://gist.github.com/140766

**Comment by chriseppstein** [comment]
Fixed.
