### ISSUE TITLE
-ms-flex-align: flex-end is incorrect, end is the correct value

### ISSUE THREAD

**Issue by mgol** [Compass/compass#1509]
I tested everything on Compass 1.0.0.alpha.17.

This is one of these things that IE necessarily confused too much. IE10 supports `-ms-flex-align: end`, whereas IE11 supports `align-items: flex-end` and `-ms-flex-align: flex-end`. Compass prints only rules supported by IE11. Since IE11 supports the final syntax, it's better to omit `-ms-flex-align: flex-end` and just generate:

``` css
{
    -ms-flex-align: end;
    align-items: flex-end;
}
```

See also https://github.com/ai/autoprefixer/issues/169

The same concerns some other properties, see http://msdn.microsoft.com/en-us/library/ie/dn265027(v=vs.85).aspx for the full list.

**Comment by cimmanon** [comment]
You already know that the Flexbox mixins only provide the standard properties because [_you_ opened an issue for this 2 months ago](https://github.com/chriseppstein/compass/issues/1427).  I have been working on new Flexbox mixins that support all 3 drafts _and_ work with the new API.  It should be ready before 1.0.0 is released.

**Comment by mgol** [comment]
Sorry, I had custom mixins in place of Compass ones in a couple of places, this was an error on my side and I didn't notice that in a hurry.
