### ISSUE TITLE
Compass watch errors on complex :not selector

### ISSUE THREAD

**Issue by deleteme** [Compass/compass#158]
To give you some context, this CSS is from the IUI iPhone library. I changed the file extension from iui.css to iui.scss so that I could benefit from file concatenation.

Below is the offending code and resulting error message from having "compass watch" process it:

CSS:

```
input:not(input[type|=radio]):not(input[type|=checkbox]) {
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    width: 100%;
    margin: 8px 0 0 0;
    padding: 6px 6px 6px 44px;
    font-size: 16px;
    font-weight: normal;
}
```

Error Message:

```
Invalid CSS after "input:not(input": expected ")", was "[type|=radio]):...")
```

**Comment by nex3** [comment]
This selector is actually invalid CSS. According to [the spec](http://www.w3.org/TR/css3-selectors/#negation), `:not` may only contain a [simple selector](http://www.w3.org/TR/css3-selectors/#simple-selectors-dfn). You're passing a [sequence of simple selectors](http://www.w3.org/TR/css3-selectors/#sequence-of-simple-selectors), since your `:not` contains both `input` _and_ `[type|=radio]`.

If this invalid CSS works on browsers, though, I'll consider adding support for it to Sass.

**Comment by chriseppstein** [comment]
closing.

**Comment by tigerofasia** [comment]
Hey chris, still getting this issue on compass 1.0.1. What's the plan mate?
