### ISSUE TITLE
Sourcemaps w/grunt and gulp-ruby-sass

### ISSUE THREAD

**Issue by grayghostvisuals** [Compass/compass#1654]
Here's the repo I'm using to test all this with : [https://github.com/grayghostvisuals/sourcemaps](https://github.com/grayghostvisuals/sourcemaps)

My Workspace in DevTools is pointed at the root directory of my project and my Sass file is mapped to the local file system resource. I could definitely be doing something wrong for sure, but again here it is live for you to see.

Gulp-Ruby-Sass w/Compass Screencast
[https://dl.dropboxusercontent.com/u/41114960/gulp-ruby-sass.mp4](https://dl.dropboxusercontent.com/u/41114960/gulp-ruby-sass.mp4)

Grunt w/Compass Screencast
[https://dl.dropboxusercontent.com/u/41114960/grunt-compass.mp4](https://dl.dropboxusercontent.com/u/41114960/grunt-compass.mp4)

**Comment by grayghostvisuals** [comment]
Also discovered from Paul Irish that basically right now if you change something in styles pane
it breaks the source mapping because Chrome doesn't really know how to update the original source values.

**Comment by chriseppstein** [comment]
@grayghostvisuals right. For instance, did you mean to change the variable that was used to make that value, construct an intermediate expression (like by pressing up 5 times did you mean to change $foo to $foo + 5), or just replace the property with a new value.

IMO, the way Grunt w/Compass works seems more correct because once you're editing the properties from the styles pane, you're not editing the scss anymore.

I'm not at all sure why they behave differently tho. Compass just calls to Sass's sourcemap generator.

Re your comments at the end of the second screencast, I agree that the in-place editing is a nicer workflow, it's not clear that the experience can be better without having Sass syntax understood natively by the browser. That you can jump to source, save, and see it reload without changing context is a pretty fantastic workflow.

**Comment by grayghostvisuals** [comment]
@chriseppstein  

> or just replace the property with a new value

new property. exactly.

Agreed on the last part. Paul said this stuff is still being worked on, but thanks again for taking a peek. The current workflow is better than it was and it will only get better in time. :beers:
