### ISSUE TITLE
Negative calculated values with parenthesis -(value) omits Zero values and spaces.

### ISSUE THREAD

**Issue by elado** [Compass/compass#174]
background-position:0 -(image-height('../images/home/create-button.png')/2);
outputs
background-position: -82px;
(No Zero).

and

background-position: left -(image-height('../images/home/create-button.png')/2);
outputs
background-position: left-82px;
(No space after "left").

However, *-1 or /-2 on the calculation makes it work.

**Comment by nex3** [comment]
This is a Sass issue, and also the expected result. If you have `VALUE1 - VALUE2`, regardless of the whitespace surrounding the `-`, that means "subtract `VALUE2` from `VALUE1`". Changing this so that it's whitespace-dependent -- that is, making `VALUE1 -VALUE2` work differently -- would be confusing and inconsistent.

If you wrap the result in another layer of parentheses, it will work.
