### ISSUE TITLE
default width/height for blueprint forms breaks rows/cols attribute

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#18]
(reported on twitter -  https://twitter.com/userscripts/status/2189080080)

http://bit.ly/EvcX4

While it can be argued that you shouldn't use the rows/cols attribute, I still think the hard-coding of dimensions in a file you're not supposed to modify is a bad idea. So we should make it configurable somehow.

**Comment by anotherjesse** [comment]
Thanks for filing this.  I wasn't sure if there was already a way to override and I was just being dense.

**Comment by tdreyno** [comment]
I've created a patch here:
http://github.com/tdreyno/compass/commit/9b1f32bd9c9a147eab9e7030eb6c02bbee630a07

However, I don't actually agree with the concept. In my opinion, Compass should not contain any defaults and users would just use Sass normally to inject the colors and sizes like normal. The problem is, that's not how Blueprint is designed. It's designed to automatically have a very solid starting place for sites. This means sites using Blueprint with CSS have a lot of duplication thus the need for Sass & Compass in the first place.

I guess the defaults that are intrinsic to Blueprint muddle up the philosophy of Sass. Hopefully this patch makes people happy, but I can't help but think the increasing complexity is turning Compass into it's own weird language which will need more and more documentation as time goes on.

**Comment by chriseppstein** [comment]
I agree. The main stylesheet provided by compass if you don't specify a framework is a reset and an empty file.

New frameworks built on Sass from the ground up are already under development and will be much more elegant to use. The compass core framework, tries to provide simple, basic mixins that are common patterns -- not anything that would make a site look presentable out of the box.

Thanks for the work, your thoughts on the matter are well founded, and your effort here is helpful.

**Comment by anotherjesse** [comment]
There are also issues trying to override a:visited since it is set in the framework. 

Perhaps a way to filter out rules on import? 

@import foo.sass remove:"css selectors here"

right now I would have to fork the blueprint framework in order to fix this.  

Or perhaps a rake task to "pull a snapshot of the framework into my app/stylesheets/framework" then I can tweak and periodically update if needed.

**Comment by tdreyno** [comment]
Overriding is easy, it's resetting or removing unwanted styles that's a hassle. I hate to inject more stuff into Sass itself, but maybe a - (minus) prefix to match the + (plus) prefix which removes information from the compiler's view of the sass structure. Obviously, I have no idea if that's even possible with the way Sass is implemented.

**Comment by anotherjesse** [comment]
I knew I should have waited until the morning to post - I mean removing a:visited

**Comment by chriseppstein** [comment]
Overriding is the way to go. The Sass compiler can trivially remove the duplication from the generated css in a future version. Maybe that should have been my response to the original request as well...

**Comment by chriseppstein** [comment]
Fixed by b84dd3031b82547cff8e1ef1f85de66d98cd162b
