### ISSUE TITLE
Comment breaks @if/@else

### ISSUE THREAD

**Issue by pixelpuppe** [Compass/compass#1837]
Using a comment one line before "@each" with the same indentation, I get the error message "@else must come after @if."

_This compiles without errors:_

``` sass
div
  @if true
    /* use red color */
    color: red
  @else
    /* use blue color */
    color: blue
```

_This throws an error:_

``` sass
div
  /* use red color */
  @if true
    color: red
  /* use blue color */
  @else
    color: blue
```

Shouldn't comments be ignored?

**Comment by lolmaus** [comment]
In the Sass syntax, block comments are indentation-specific and the closing `*/` thingie is optional.

Everything that is indented below a block comment, is considered to be part of the block comment.

You can do:

``` sass
body
  foo: bar

  /* Say hello
     to luxury,
     my pretty-pretty

  baz: quux
```

Demo: http://sassmeister.com/gist/2608b07a2ea6ac6936f4

PS: It is generally advised not to use block comments to annotate Sass code. Use them only for passing license info and temporary debug info.

**Comment by pixelpuppe** [comment]
I tried to use single-line comments, but the same error occurs ("@else must come after @if.")

``` sass
div
  // use red color
  @if true
    color: red
  // use blue color
  @else
    color: blue
```

**Comment by lolmaus** [comment]
Oops, your problem is a bit different. I'm sorry.

Sass expects an `@if` node to be followed by an `@else` node on the same level of indentation. You have a comment node instead, so Sass considers `@if` complete. And then there appears a stray `@else`.

I think it's a legit bug.

In other languages it is very common to comment if clauses like this:

``` rb
# Try something...
if foo
  bar

# In case it failed...
else
  baz
```

It's a shame that Sass indented syntax does not allow that. Unfortunately, it's maintained with the lowest priority, so don't expect a quick fix.

**Comment by scottdavis** [comment]
This issue should probably be moved to the sass issue tracker
