### ISSUE TITLE
Remove old sprites when a new sprite is created

### ISSUE THREAD

**Issue by roytomeij** [Compass/compass#255]
Unless I'm misunderstanding some internal workings of Compass, removing old sprites when a new one is generated saves us from ending up with dozens of sprites after a while.

**Comment by chriseppstein** [comment]
This cannot be done unfortunately. This is because you can make several spritemaps from one sprite directory. These could have been done in other stylesheets with slightly diff params or by using globbing to select different sprites. 

Best solution I have so far is to remove all sprite maps and then recompile. There's another issue open to do that.
