### ISSUE TITLE
Webkit linear gradients don't support pixel color-stops

### ISSUE THREAD

**Issue by MyHealthTeams** [Compass/compass#287]
Linear gradients specified with pixels for color stops work in Firefox but not in Webkit.  This is a blocking issue for us.

```
th.linear {
  @include background-image(linear-gradient(white, red 50px)); 
}
```

**Should produce (for webkit):**

```
th.linear {
   background-image: -webkit-gradient(linear, 50% 0%, 50% 50, from(white), to(red));
}
```

I've checked out the code and will look at how to fix it, but it'd be nice if someone more familiar with the problem/potential solutions would help.

**Comment by chriseppstein** [comment]
Will get this fixed in the next release.

**Comment by sdhull** [comment]
Awesome!! That's exciting.

We have a deadline in about 1 week, and I'd love to have this fixed for that release.  Was wondering if you will be getting to this in the next few days or if I should take a pass at it in the interest of expediency...

**Comment by chriseppstein** [comment]
I'll take a peek very soon and try to understand if it's a simple issue or not, then I will be able to tell you.

**Comment by sdhull** [comment]
The only real way to make gradients stop at a particular pixel value in webkit (at least the version of webkit that almost everyone is using) is to specify the size of the box.  Sadly, color-stops in webkit still have to be done in percentages, but if you tell webkit that the box is only say 200 pixels high, then you can know that your gradient will be done in exactly 200 pixels.

I _think_ that you could assume that the box should be only as big as the last color-stop (assuming that color-stops have been passed in pixels).  I'm fairly certain that this would work perfectly as long as your gradient starts at either the top, the left, or even the top left. But I _know_ that it would totally fall over if your gradient started at the bottom or the right.

Alternatively linear-gradient could just take a separate optional argument that would only be used for webkit and that would be used instead of calling `grad_point(opposite_position(position_and_angle || Sass::Script::String.new("top")))`.  It's a little uglier (you would see the same value twice in most cases when people were using it), but at least you could brute-force gradients that needed to start at the bottom or right side of a box.

I'm going to try the first approach now and just fallback to current behavior if the start position is bottom or right or 'bottom right'.

**Comment by sdhull** [comment]
This is the first approach I was talking about:

https://github.com/chriseppstein/compass/pull/305

**Comment by chriseppstein** [comment]
merged in. Thanks!

**Comment by MyHealthTeams** [comment]
Excellent!  Thank you!
