### ISSUE TITLE
Blueprint form alignments

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#29]
The fields of blueprint forms are not the same within compass as they are in blueprint.

**Comment by mrship** [comment]
I posted a revised forms.html.haml to the Compass google groups that should be useful for testing this once fixed. HTH.

**Comment by chriseppstein** [comment]
That file is now part of the compass/examples/blueprint_default example. Now we just need a fix ;-)

**Comment by enricob** [comment]
Sorry it has taken me so long to get around to this but I've finally taken some time to look into these issues. It seems that the inline form mixin wasn't getting applied to `form.inline` in the example, so I've fixed that in the master branch of my fork.

This fixes the alignment of all of the elements except for the submit button, which for some reason is way up. I haven't been able to track it down but it's probably outside of `_form.sass`, since `_form.sass` doesn't contain any styles that directly affect the button.  =(

**Comment by wakiki** [comment]
Is there any update to this?

**Comment by enricob** [comment]
I haven't been able to solve it yet and I currently can't allocate time to look into it further.  >_<

**Comment by chriseppstein** [comment]
I applied Enrico's patch and then I poked around for a while. It's very strange. I can't find any CSS difference that matters. But I did find that I could make it render correctly if I added a non-breaking space.

http://github.com/chriseppstein/compass/commit/81942836d095a7a82fb4ddc966bb40eea6b9345b

I think it looks pretty good. If this issue is troubling others enough for them to find the root cause, I'd be happy to accept their patch/fix in any form.
