### ISSUE TITLE
weird issue - change detected - identical

### ISSUE THREAD

**Issue by damien-roche** [Compass/compass#314]
it says: 

Change detected to: /path/to/css
identical public/css/dashboard.css

..and none of my changes are reflected in the created file. in fact, the file is now blank. 

On ubuntu 10, ruby 1.8, gems 1.3.5..please, sort it out! Framework is useless if it buckles under simple tasks like this.

**Comment by chriseppstein** [comment]
Please include the contents of your sass file, your configuration, and the actual command that you ran and the output it displayed.

**Comment by chriseppstein** [comment]
And does running `compass compile --force` fix things?

**Comment by damien-roche** [comment]
Hi, I'm not entirely sure that matters. The issue still stands - when
'watching', the tool reports identical file when the file is not, and so
sees no reason to update it. I have to manually delete the file every time.
This happens very sporadically. I think it usually happens after a couple of
fast edits and saves.

**Comment by chriseppstein** [comment]
I'm not inclined to help you, given your attitude in this report. I asked for information because I felt I needed it to diagnose the issue.

**Comment by damien-roche** [comment]
I'm sorry, I'm not looking for help - I'm trying to help you create a better
piece of kit!! JEEZ. I didn't notify you as a dig, I did it because that's
what I'd want someone to do. Really man, chill out. Suck it up, your tool is
buggy, sort it out. Simple.

**Comment by chriseppstein** [comment]
I'm not upset. You are. The watcher works fine for just about everyone else, so this issue is likely specific to your project or system. This bug report does not include enough information to properly reproduce the issue and so it is useless. I asked for the information I would need to attempt to fix the issue and you declined to provide it.

**Comment by hoopyfrood** [comment]
Hi Chris,
I'm running the same spec as ivrock and used to get the same issue when uploading large sass files over sftp/ssh tunnels. Then I switched from Dreamweaver to TextMate, turned on atomic saves and have never experienced the issue since. It would seem compass watcher kicks in as soon as a change is detected, not necessarily when the upload is finished/file is 100% on the server. As I mentioned this only occurs on remote machines where latency plays a role. I don't think it is necessarily a compass issue, just wanted to provide steps to reproduce.

PS: my SASS files would be 20, 30+kb, failing consistently with "identical file", so after each upload I would change a line in a much smaller included _sass file to get compass to trigger again essentaily resolving the issue.

Compass rocks!

**Comment by ttilley** [comment]
it is rather unfortunate, but i am unable (within FSSM) to catch the moment a write has completed except under linux using the inotify backend. the mac filesystem event system is only at the directory level, and polling could hit a file at any point and just notice a change (file size, timestamp). it's... complicated.

so yes, you need to either use a linux box with inotify or an IDE/editor feature for doing atomic writes (where it actually writes elsewhere and renames when finished) to always be 100% certain you won't hit this bug. normally the latency period is high enough, and writes are fast enough, where this isn't an issue. the "common" case shouldn't be bitten by this.

...I guess another option would be to increase the latency period from half a second to a second or more?

**Comment by hoopyfrood** [comment]
Agreed with ttilley. Never experienced an issue developing locally on Mac, only over sftp on Linux. And yes, the common case shouldn't be affected by this.

**Comment by chriseppstein** [comment]
Thanks for your input guys. I don't think this issue is related to remote editing, so perhaps you can open a separate issue for that and link here for details.

Also, since I don't have an environment set up in this configuration, it's going to require detailed steps to set that up or just provide a patch that clears up the issue for you.

**Comment by damien-roche** [comment]
To note, I now use manual compile. I'm sorry for my past messages. You're right, my attitude stunk. Didn't mean to come across like that, was just a bit irked about the issue.

Of course, compass is free and is _fantastic_. I should be thanking you! :)

Do you have any update on whether this issue is resolved or if you've had anybody else report similar issues?

**Comment by gunta** [comment]
I'm having this issue also.
Using MacOS X 10.6.8 + Macfusion SFTP + Espresso 2 editor.

**Comment by ttilley** [comment]
interesting. i had thought that this was a MACFUSE-exacerbated oddity. all of the apple-supported filesystems fire an event both on the start of write and the end if events fire before writing is finished. sshfs doesn't appear to.

...ok, I just looked up macfusion and it is ALSO using MACFUSE. I may need to add filesystem detection support and throw a warning to stderr if you monitor a non-apple-supported filesystem. At the least I should warn that high latency filesystems combined with potentially incomplete events from MACFUSE may result in incorrect behavior.
