### ISSUE TITLE
Provide info for Heroku compatibility in docs

### ISSUE THREAD

**Issue by olivierlacan** [Compass/compass#342]
Heroku is widely used for Rails projects running the Compass gem and even though I'm aware that it's a read-only environment (where you can only compile inside of the tmp/ folder of a Rails app) I often forget this while creating a new project using Compass.

Chris, as I mentioned on Twitter the Install page on the beta docs would be a good place to warn users who select "Rails project", but the Rails setup part of the Help section could be a good candidate as well.

Here's the Heroku Dev Center page dedicated to this issue with a nice fix (environment agnostic) : http://devcenter.heroku.com/articles/using-compass

PS: I won't go so far as to propose that the fix be suggested when executing "compass init" but that could be a very straightforward way of avoiding fumbling and support requests.

**Comment by jaryl** [comment]
I just tried this out and ran into a couple issues. Firstly, the sass directory is wrong because compass sets up rails projects with the sass files in the app folder, thus it should be:

```
sass_dir  = 'app/stylesheets'
```

Secondly, the initializer wouldn't work because compass now runs as a railtie and it doesn't want to be initialized twice and gives a warning as you start up. I'm not sure if it affects anything in runtime, but I remove warnings when I see them because that's how I roll. If you're anything like me, delete or comment out this line in the initializer:

```
Compass::AppIntegration::Rails.initialize!
```

Edit: I will be asking Heroku to update their documentation too.

**Comment by chriseppstein** [comment]
In 0.12, compass works with the rails asset pipeline -- no special instructions are needed.
