### ISSUE TITLE
Any way to generate a sprite image horizontally?

### ISSUE THREAD

**Issue by kimili** [Compass/compass#366]
Currently, the individual sprites in the generated sprite images are arranged vertically. This creates an issue in certain situations - for instance:

Say you have modules in a layout of fixed width but variable height. Each of these modules has an icon in the upper left corner, icons which you want to sprite. With the current functionality, in order to use a generated sprite in this situation and minimize the chances of the next sprite image peeking up at the bottom of a tall module, you have to put a whole bunch of space between the sprites to accomplish this - more than is ideal. If the sprites could be arranged horizontally, you could simply use the module width as the sprite spacing and be done with it.

Additionally, it seems that for [best performance](http://developer.yahoo.com/performance/rules.html#opt_sprites), sprites should be arranged horizontally and should minimize the space between sprite images.

Perhaps we can add a sprite map configuration option to dictate in which direction the sprites are laid out.

**Comment by kathi** [comment]
this feature would be really great and would help me a lot.
thanks :)

**Comment by jgarber** [comment]
This would help me out too! Thanks!

**Comment by scottdavis** [comment]
describe a use case and it will be considered

**Comment by jgarber** [comment]
Okay, a site I'm re-working right now, http://tinefcon.com/, uses a horizontal navigation (and I'm using +horizontal-list) with background images for normal and hover states. The background images are different heights and involve transparency. When I first fed the images in, the shortest item (Testimonials) had a few pixels of its hover image visible beneath it. I fixed it with `$nav-spacing: 20px;` (or I could have just made all the images the same size in Photoshop). **But, since they have variable heights and involve transparency, the most space-saving option would be to have them laid out horizontally in the sprite.**

**Comment by scottdavis** [comment]
mind making a visual example of how they would be packed? if i make this an option i will need some visual guide since im a code monkey =)

**Comment by jgarber** [comment]
Basically, it's just switching it to arrange the pieces horizontally rather than vertically. It's a common option for sprite generators like http://spritegen.website-performance.org/ for example...

Horizontal
<a href="http://tinypic.com?ref=16ii2ba" target="_blank"><img src="http://i52.tinypic.com/16ii2ba.png" border="0" alt="Image and video hosting by TinyPic"></a>

Vertical
<a href="http://tinypic.com?ref=dljdkh" target="_blank"><img src="http://i53.tinypic.com/dljdkh.png" border="0" alt="Image and video hosting by TinyPic"></a>

Except I wouldn't need any padding between pieces if the were horizontal (that particular generator wouldn't let me do without padding).

Also, as kimili points out above, the Yahoo! performance folks recommend horizontal for better compression.

**Comment by scottdavis** [comment]
well i am working on a smart way to pack sprites (bin packing) which if you want a small file is the best way to go its implementing the other controls that nico specced out that are hard

so this is purely cosmetic? its not breaking your sprite maps if they are vertical (im trying to understand fully whats going on)? can you gist the sass file for your sprites? im trying to wrap my head around the total problem

**Comment by kathi** [comment]
my usecase is, that i have a div which can grow in height depending on the user content with constant width. this whole div is clickable and switches the bg image on hover. if the div is getting to high another image in the sprite is getting visible - which isnt so good. so spacing doesnt help me fixing the problem, because setting the spacing that big, that it could not happen that any other picture get visible would end in a huge file with much free space. 

so the horizontal aligning of the images would really help me in this usecase.

**Comment by scottdavis** [comment]
seems like a fair use case ill bump this up the list and get this implimented

**Comment by kathi** [comment]
thanks :)

**Comment by scottdavis** [comment]
https://github.com/chriseppstein/compass/commit/43868ecabd856b812f805ac7bb983f47c94f8d0f#L1R609
