### ISSUE TITLE
Bug: Found IE bug with inline-block mixin

### ISSUE THREAD

**Issue by joshjhall** [Compass/compass#40]
Appended the last line to the current inline-block mixin to fix IE6 / IE7 display.  Seems to be working fine for me, but might require additional testing.

```
=inline-block
  :zoom 1
  :display inline
  :display -moz-inline-box
  :display inline-block
  :vertical-align top
  :*display inline
```

**Comment by chriseppstein** [comment]
That the +inline-block mixin doesn't work on block elements in IE6 & 7 is a known issue. If someone gives a well tested solution that works across a broad array of both inline and block elements, I will accept that patch.

However, I would encourage you to revisit the choice to use a block level element, in many cases a span is more semantically correct for an inline-block based layout.

**Comment by ttilley** [comment]
please test my fix that was [posted to the newsgroup](http://groups.google.com/group/compass-users/browse_thread/thread/5837fbc002575b75/a6f5c023c682345f?lnk=raot#a6f5c023c682345f).

```
=inline-block 
  :display -moz-inline-box 
  :-moz-box-orient vertical 
  :display inline-block 
  :vertical-align middle 
  :#zoom 1 
  :#display inline 
  // fixes alignment against native input/button on IE6 
  :#vertical-align auto
```

**Comment by chriseppstein** [comment]
This implementation was also posted:
    =inline-block
      :display -moz-inline-box
      :-moz-box-orient vertical
      :display inline-block
      :vertical-align middle
      :#display inline
      // fixes alignment against native input/button on IE6
      :#vertical-align auto

Can someone please explain why the `:#zoom 1` style is needed or not?

**Comment by chriseppstein** [comment]
I found [this post](http://www.webmasterworld.com/css/3649638.htm) on the subject. They use conditional comments to target IE < 8, is that what the # hack does?

**Comment by ttilley** [comment]
rules with # will target IE6+7. rules with \* will target IE6, but not 7. IE8 seems to have significantly more sane support of CSS in general... not only do the old hacks not work, but most of the time they aren't needed either.

as for the version you post second... the zoom is there to trigger hasLayout engine. inline-block in IE6+7 just triggers hasLayout for inline elements. you can achieve the exact same effect without using inline-block by making it display inline and then triggering hasLayout (like with zoom). that's why the hack works on both inline and block level elements, whereas inline-block in IE6+7 will only work for inline elements.

**Comment by ttilley** [comment]
ah, i see what you mean with that post. what happens there only happens because it's in two separate css blocks. the first block sets it to inline-block, _which triggers hasLayout_. the second block sets it back to display inline, without un-triggering haslayout because it's done in a separate block. if it was one rule, that would not work. it would instead ignore the inline-block and use the inline statement... never triggering hasLayout.

**Comment by ttilley** [comment]
in short, you can do without the zoom part only if you're using multiple css rules to do it. it our situation, this is not the case. you need the zoom.

**Comment by chriseppstein** [comment]
Using `&` in our mixin will allow us to generate two selectors that are the same. I use this trick in the +clearfix mixin. But it seems with any complex selector that would result in more generated css, not less.

**Comment by ttilley** [comment]
chris - use whatever technique you believe to be the most elegant solution. personally... i cheat. i cheat like crazy. i cheat either by using a rails plugin or dojo to add css classes to the html element representing what browser the client claims to be, what os, etc. it lets me avoid css hacks entirely without using conditional comments (which i would not be able to use to target firefox2, for example). it's unfortunate that such a solution is out of the scope of what sass, and compass, could provide. i mean... it makes the selectors themselves more specific, so you could theoretically run into problems. dojo's own inline-block hack is pretty much the same as the one i posted, without the additional firefox2 fix, so as to avoid css specificity issues.

**Comment by chriseppstein** [comment]
I'm not looking for elegance. Just trying to find a reasonable balance in this effed up world of hacks that we live in. Thank you for your contribution and explanation. I think adding a class to the document body that indicates browser is a nice solution, but not general purpose enough.

**Comment by chriseppstein** [comment]
I've merged a fix for this into my local edge. It will be part of the v0.10 release.

**Comment by timomeinen** [comment]
The line

:*display inline

should be removed completly, as it breaks the inline block in IE6 and IE7. The inline-block-Mixin is working correctly, without the '_display inline'. But adding it at the last line of the mixin, it overrides the display inline. You can check this with the inline-block sample on your page. IE8, Firefox, Safari ignore the '_display inline', but IE6 and IE7 don't style an inline-block with this.

If you don't want to remove this element, could you please explain, why it is included?

Thank you.
