### ISSUE TITLE
Unable to center a sprite in a map

### ISSUE THREAD

**Issue by curvedmark** [Compass/compass#415]
After @import "images/*.png", setting $<map>-<sprite>-position to 50% doesn't cause the sprite to be centered in the map.

I guess it's because 50% is not a supported value? Will it ever be supported?

**Comment by scottdavis** [comment]
whats the use case? why 50% the sprite canvas size is variable and centering an image with a percentage may create different results if you add more files

**Comment by curvedmark** [comment]
Since compass adds sprite images vertically, centering a sprite image horizontally shouldn't create different results.
My use case is sometimes I'd like to horizontally center a sprite image in my background, and it would be great if compass will let me center it in the sprite map, just like it allows me to put a sprite image to the right side of the sprite map.

**Comment by scottdavis** [comment]
patches accepted =D

**Comment by ashnur** [comment]
I would gladly write a patch for this ( because I need it too), if I would know where to start. Any suggestions?

**Comment by scottdavis** [comment]
its a rather complicated problem are you able to get into irc and ill show you were to start

**Comment by ashnur** [comment]
#compass on irc.freenode.net?

**Comment by scottdavis** [comment]
Yes

Scott Davis

**Comment by curvedmark** [comment]
@ashnur told me that 50.0% might work, and it's true. By specifying 50.0% instead of 50%, the sprite image can be centered.

**Comment by scottdavis** [comment]
oh weird this sounds like possibly a sass bug in the unit parser? or maybe a feature @chriseppstein??

**Comment by ashnur** [comment]
I am not sure what this is, but I would say it is a bug. There is a division in the file you showed me, line 41, where the value you set is divided by 100 and as both part of this expression are integers, the result is also an integer, so in example 99/100 is 0 and not 0.99. That's why 100% works, and i guess numbers bigger than 100% and smaller than 200% also work(give back 1 and not 0). But it is not a percentage value just left or right alignment. If you want percentage you must set a float.
