### ISSUE TITLE
rails 3.1 issues

### ISSUE THREAD

**Issue by alec-c4** [Compass/compass#459]
Hi,
i workin' on rails 3.1 application and found following problem - if i use name /app/assets/stylesheets/**application.scss** instead of **application_.css_.scss** there are problems with using stylesheet_link_tag "application" - application.css file not found. Could you also enable support for files without .css in the middle? Also - i think it will be very useful to remove line

```
 css_dir = "public/stylesheets/compiled"
```

from compass.rb file if rails is detected as 3.1. Also can be changed line

```
 sass_dir = "app/assets/stylesheets"
```

(added assets to the path) in the same case.

**Comment by nevir** [comment]
This might be an issue to raise over on the rails (or sprockets) projects too - since that naming scheme is really enforced by Rails proper.  (Maybe template extensions should have an optional default content type)

(It could get confusing where some plugins recognize `file.format.template` and others handle just `file.template`).  Don't forget rails supports things like `application.css.scss.erb` if you want to layer multiple templating languages together (which I think is the original reason for having both extensions)

**Comment by chriseppstein** [comment]
All css files in rails 3.1 that are processed via the asset pipeline must have the `.css` extension part in them. That is a rails convention and Compass is adhering to it.

**Comment by chriseppstein** [comment]
The remaining issues discussed here are a dup of #337.
