### ISSUE TITLE
Cache busting query params not being included on absolute paths

### ISSUE THREAD

**Issue by brynary** [Compass/compass#481]
Our .sass file contains:

```
background-image: image_url("/images/new/e20/header_bg.jpg")
```

Also, we have a cache buster configured in config/compass.rb:

```
$LOAD_PATH.unshift("lib")
require "active_support/all"
require "e20/ops/revision"
require "e20/deployment/asset_cache_buster_generator"

# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "public/stylesheets/compiled"
sass_dir = "app/stylesheets"
images_dir = "public/images"
cache_dir = "tmp/sass-cache"

revision = E20::Ops::Revision.new
asset_path_generator = E20::Deployment::AssetCacheBusterGenerator.new(revision)
asset_cache_buster(&asset_path_generator.method(:call))
```

When compass compiles our Sass, there is no cache busting param added on to the URL.

We believe we have a lead on the bug, but could not solve it. From  lib/compass/sass_extensions/functions/urls.rb:

```
elsif absolute_path?(path)
  # Short curcuit if they have provided an absolute url.
  return Sass::Script::String.new("url(#{path})")
end
```

The comment appears to conflict with the implementation. It seems this should be checking an absolute_url? method instead of absolute_path?. In our case, we have an absolute path, but not a URL, so we'd expect cache busting to be applied. Here is the absolute_path? implementation:

```
def absolute_path?(path)
  path[0..0] == "/" || path[0..3] == "http"
end
```

So we believe our cache buster isn't being applied due to the first part of this conditional. (Additionally, we noticed if someone has an http.png they would get incorrect behavior. :)

Finally, while in the debugger we noticed image-url and image_url seem to run different codepaths. Is this intended?

Thanks,

-Bryan

**Comment by chriseppstein** [comment]
The `image-url` helper expects a path relative to your images directory, E.g.:

```
background-image: image_url("new/e20/header_bg.jpg")
```

Is it the case that these images are being served without being stored in your project's images directory?

In normal usage of compass, you can't generate a cache buster for root relative urls because we can't pass a filesystem path to the `asset_cache_buster` block.

I think I need to know more about what's going on before I can decide how to proceed.

**Comment by chriseppstein** [comment]
@brynary Sorry it's taken so long to get to this, I think you've moved on. But if you can remember what approach you were using for invalidation where you didn't need access to the file on disk, I'd consider a feature to support this. closing for now, though.

**Comment by satazor** [comment]
@chriseppstein I came across with this issue too.

I have a symfony project that is organized in bundles. Each bundle has his own compass project. Though, we have a CommonBundle that has common images that may be accessed by other bundles. So we must be able to reference images from the CommonBundle within other bundles. Relative urls can't be used here because the final bundle directories do not respect the source folder structure so they must be referenced by their absolute paths. We want to be able to generate the cache buster for those images also. Can an option (true/false) be implemented in the image_url to force the cache buster to be appended (defaulting to false to be BC)?
