### ISSUE TITLE
Unchanged errors not showing

### ISSUE THREAD

**Issue by alindsay55661** [Compass/compass#489]
I just updated compass and noticed the following behavior.  When I compile a file that has errors the errors will display in the terminal.  I compile a second time it lists the file as unchanged but doesn't display the errors.

I believe this is a bug as the errors should display irrespective of whether or not a css file has already been compiled.  Often time developers will check out the file and try to compile a project with errors.  If a css file already exists they don't see those errors and it takes a while to track them down.

**Comment by chriseppstein** [comment]
In order to do this, in development mode we'd have to search the css output for content that looks like an error. In production mode, we'd have to assume zero length css files had errors. then in these cases we would treat the file as if it was passed `--force`. If the files being changed are unrelated to this, it will cause a technically "unnecessary" delay. It's not clear to me what the right behavior would be in "watch" mode -- probably not recompiling the errors as user's rely on the in-browser notification in that case.

**Comment by MarioRicalde** [comment]
The errors displays in the browser still right? I believe that one single notification of the error is good enough. I mean, that's like a "something went wrong" kind of notification on the console. Also, when there's an error on the browser, all the styles will die so it's really visible.

**Comment by chriseppstein** [comment]
all that is true, but I'm not convinced that we shouldn't do it. I've been tripped up by this when the page I'm working on is not using the stylesheet that has the error.

**Comment by scottdavis** [comment]
this tripped me up literally 5 minutes ago +1

**Comment by scottdavis** [comment]
maybe we should check the files to see if they contain an error string even if its unchanged?

**Comment by chriseppstein** [comment]
This is fixed in `1.0.0.rc.0`
