### ISSUE TITLE
https, IE7, and SVG causing "mixed content" warning dialogs

### ISSUE THREAD

**Issue by Zettersten** [Compass/compass#536]
Please reference this issue on Modernizer for more details and possible solutions,
https://github.com/Modernizr/Modernizr/issues/218

On an https enabled domain - IE7 users get a "Mixed content" warning when CSS contains SVG data URI's.

Compass spits out: 

``` css
background:url('data:image/svg+xml...')
```

Paul Irish suggests the following:

``` css
background:url('//:image/svg+xml...')
```

Where the term "data" goes away and is replace with two forward slashes.

Please review the finding in the link above.

**Note:** For some extra clarification, understand that I am not trying to use SVG to provide an IE7 gradient solution but instead to provide an IE9 solution. This is what results in error. Anywhere there is "data uri's" on an https domain IE7 will throw a "Mixed Content" warning dialog.

**Comment by Zettersten** [comment]
I'd like to mention that the solution above only works for embedded **fonts (@font-face)**, not data images.

**Comment by chriseppstein** [comment]
ugh. this is such a clusterf*ck. IE7 is on it's way out. I don't see a clean implementation for it. Can you put your svg files in a different stylesheet and use conditional comments to load them or try some selector/browser hacks to hide this from IE7?

**Comment by Zettersten** [comment]
I ended up doing so - thanks for the input. I'm not sure the solution above is a working one.

**Comment by scottdavis** [comment]
closing since it was resolved

**Comment by seanadkinson** [comment]
For anyone else that finds this issue trying to resolve the mixed content warning, here is how we fixed it.

First, we have `<html class="ie7">` rendered with conditional comments (typical html5-boilerplate method).

Then we also have an IE7 specific mixin, defined as follows:

```
@mixin ie7() {
  @at-root {
    .ie7 & {
      @content
    }
  }
}
```

This will take any styles, and put them in there same hierarchy, but under "`.ie7` at the start.

Now for each `background-image` with a gradient, we unset it for IE7.  Example:

```
.blue-bg {
  @include background-image(linear-gradient(to right, $my-blue, $my-lt-blue));
  @include ie7() {
    background-image: none;
    background-color: $my-lt-blue;
  }
}
```

This fixed the mixed content warning, since the `background-image: none` overwrites the `background-image: url(data/...)`.
