### ISSUE TITLE
underline.png in vertical_rhythm is missing

### ISSUE THREAD

**Issue by jonassmedegaard** [Compass/compass#599]
The mixin debug-vertical-alignment by default use underline.png but that file is nowhere to be found in the source of Compass.

**Comment by scottdavis** [comment]
@ericam do you have the png file hiding someplace?

**Comment by mirisuzanne** [comment]
Nope. Sorry. Don't know where that came from or where it went to. 

But it wouldn't be very useful if it was there, because it needs to match your actual site settings. You really should be making your own or using the new grid background module. Compass does include a simple way to make your own in the command line: 

```
compass grid-img W+GxH [path/to/grid.png]
```

(Width + Gutter x Height)

I'd recommend changing debug-vertical-alignment so it becomes a shortcut for baseline-grid-background, but allowing both to take an (undefined by default) image argument as fallback for older browsers. I'd also add a note in the docs pointing to the grid-img command line tool. Not sure how soon I can get to it, but if someone wants to submit a patch I'll be happy to look it over.

**Comment by scottdavis** [comment]
ok ill move this to the 0.12.1 milstone

**Comment by barraponto** [comment]
@ericam can't we use the `on_style_saved` callback to generate this file? Trying to use it out of the box and missing an image file is frustrating.

**Comment by scottdavis** [comment]
I think what he was getting at is everyone's underline.png is different

**Comment by mirisuzanne** [comment]
@barraponto It is certainly a problem for things not to work out of the box. But right now we have a bug (missing file) and a broken approach (an image that should be different for everyone). I'm suggesting we fix the approach, not just the bug.

**Comment by barraponto** [comment]
@ericam well, on_style_saved callbacks would fix it while we change the approach. If I knew how to get a Compass plugin to modify the values in config.rb, I'd write a patch.

BTW, I believe we can try generating the grid with repeating gradients, what do you think?

**Comment by mirisuzanne** [comment]
We already are using gradients for the grid-background mixins that I'm proposing we use here. We aren't using repeating gradients because they can't account for the concept of a side-gutter. Though we could use some logic to create simpler repeating gradients (less code) when there are no side-gutters (or they are equal to the internal gutters). 

Compass doesn't actually have built in support for repeating gradients yet, right? Or did I miss something?

**Comment by barraponto** [comment]
@ericam no support for repeating gradients, although @chriseppstein did post a workaround on #401

**Comment by mirisuzanne** [comment]
https://github.com/chriseppstein/compass/pull/615
