### ISSUE TITLE
Cannot Concatenate Strings in @import

### ISSUE THREAD

**Issue by parkr** [Compass/compass#613]
I cannot seem to use variables when using the `@import` command. I have 2 different styles (white & red) that I want to choose from. At the moment, I have:

`screen.scss`:

``` css
@import "main";
```

`main.scss`:

``` css
$banner_color: "white";
@import "partials/identity";
@import "partials/search";
```

`partials/_identity.scss`:

``` css
@import "identities/cu-" + #{$banner_color};
```

`partials/_search.scss`:

``` css
@import "identities/search-" + #{$banner_color};
```

And I get this error when running `compass compile`:

``` bash
error sass/screen.scss (Line 1: Invalid CSS after "@import ": expected uri, was "identities/cu- ...")
```

It doesn't look like the variable is being properly concatenated. I tried interpolation (`@import "identities/cu-#{$banner_color}`) but that fails too... Looks like a bug to me!

**Comment by chriseppstein** [comment]
This is technically a sass issue, but it's one that we've already addressed numerous times. Imports cannot be dynamic because that would prevent us from determining dependencies via static analysis of the file which makes a lot of things annoying and slow. I've rarely seen a sitation where the code cannot be restructured to accomodate this limitation even tho dynamic imports would certainly be a nice way to implement things from time to time.

**Comment by parkr** [comment]
Ok, thanks!
