### ISSUE TITLE
sprite doesn't add repeat-x

### ISSUE THREAD

**Issue by antpaw** [Compass/compass#614]
Hi, this code works well, but i just ignores the repeat-x part. i have no idea what I'm doing wrong

```
$icon-repeat: repeat-x

@import "icon/*.png"
@include all-icon-sprites
```

generated code (i've extended some classes inside sass)

```
.icon-sprite, .icon-delete, .icon-delete_h, .icon-edit, .icon-edit_h, .icon-hot, #main_navi li.hot a:before, .icon-map, #main_navi li.map a:before, .icon-move, .icon-move_h, .icon-news, #main_navi li.news a:before, .icon-search, #head_sidebar #head_search label, .icon-search_a, #head_sidebar.autocomplete_menu_open #head_search .search_node label, .icon-user_dropdown, #head_sidebar #user span:after, .icon-user_dropup, #head_sidebar.settings_menu_open #user span:after {
    background: url(/assets/icon-s76182648f7.png) no-repeat;
 }
```

gem:
    compass (0.12.alpha.0)
      chunky_png (~> 1.2)
      fssm (>= 0.2.7)
      sass (~> 3.1)

**Comment by chriseppstein** [comment]
hmmm. @hagenburger can you weigh in?

**Comment by hagenburger** [comment]
There are 2 different `repeat-x` types: the CSS value and the image generation value. Your code should enable the sprite generator to place the image several times in one line in the sprite image if the width is smaller than the total width. 

If you want to use the CSS `repeat-x` you have to do this by yourself, e.g.:

```
.icon-sprite
  background-repeat: repeat-x
```

(Do not use `background` unless you want to override the generated code. All `.icon-*` classes will be added on the fly because of `@extend`.)

**Comment by antpaw** [comment]
okay tbh i dont understand your answer, because i don't see a the point, why not just fix this bug?

but it doesn't matter anymore to me, because i've found a better way to implement the compass sprites

```
 $icons-spacing: 20px
 $icons: sprite-map('icons/*.png')
  .name
    background: sprite($icons, version_dropup, 0, 2) no-repeat
```

the problem is, the spacing gets ignored once again.
it would be great if you could fix this too

**Comment by chriseppstein** [comment]
If you create the sprite-map like that you need to pass $spacing: 20px as an argument. It's not a bug. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by hagenburger** [comment]
> okay tbh i dont understand your answer, because i don't see a the point, why not just fix this bug?

This is not a bug, this is a feature but difficult to explain. So it may be a “bug” in the documentation which I should improve.

**Comment by antpaw** [comment]
okay now i get it, well as you've said the documentation is very misleading. but i think i got the hang out of it now and it rocks. thanks guys!

**Comment by tonytopper** [comment]
If I am reading this right there is no way to change the CSS generated by compass from no-repeat to repeat-x.  And the repeat configuration variable is in fact not related to CSS.  This seems unintuitive.

**Comment by chriseppstein** [comment]
Are there cases where the image should be repeated in the sprite but not repeated in the `background-repeat` property?

**Comment by developer-collin** [comment]
I'm here just to comment and validate this as being a seriously confusing issue. The documentation doesn't mention anything about repeat-x being an "image generation value" opposed to a "CSS value". Since repeat-x is a CSS property, it is only natural to assume you're setting the CSS value. Add that on top of all of the sprite customization options varying back and forth between being options for image generation and css properties, it is beyond confusing. A real obstacle and turn-off to anybody trying to start using Compass.

My suggestion would be to:
1st) Fix the documentation. Separate image manipulation customizations from css customizations. Or at least make it clear what each does.
2nd) Make the code smarter. If you're using repeat-x on image manipulation, I'm inclined to believe repeat-x should also be on set on the CSS the majority of the time. If somebody has a case that's an exception to that, it makes more sense for them to override the typical scenario. Similarly, add another variable to control the CSS value.
