### ISSUE TITLE
0.12.alpha.1 spriting issue

### ISSUE THREAD

**Issue by aaronchi** [Compass/compass#625]
When upgrading to 0.12.alpha.1 in a Rails 3.1 app, I get errors like this trying to generate sprites:

```
Invalid argument - c:/sites/relatespace/tmp/sass-cache/e7e4fc9c273e9ad688df0cda3d66b12f23868f9f/*.pngc
```

This is working in 0.12.alpha.0

**Comment by scottdavis** [comment]
Clear your sass cache

**Comment by aaronchi** [comment]
Same issue after clearing cache. It doesn't seem to be able to generate sprites.

**Comment by scottdavis** [comment]
can you make me a test project that triggers this ill have to find a windows machine to test on until then i would go back to the previous version

**Comment by aaronchi** [comment]
added here:

https://github.com/aaronchi/Compass-Issue-625

**Comment by scottdavis** [comment]
now to find someone i know with a windows machine =)

**Comment by scottdavis** [comment]
Well this is working on my mac so that limits this to a windows issue i think

<pre>
[sdavis@sdavis:Compass-Issue-625 (master)]$ bundle exec rake assets:precompile
/Users/sdavis/.rvm/rubies/ruby-1.9.3-p0/bin/ruby /Users/sdavis/.rvm/gems/ruby-1.9.3-p0/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
/Users/sdavis/.rvm/rubies/ruby-1.9.3-p0/bin/ruby /Users/sdavis/.rvm/gems/ruby-1.9.3-p0/bin/rake assets:precompile:nondigest RAILS_ENV=production RAILS_GROUPS=assets
[sdavis@sdavis:Compass-Issue-625 (master)]$ ls public/assets/
application-795594bda338bbc7b5aeb71bdba45db3.js     application.js.gz
application-795594bda338bbc7b5aeb71bdba45db3.js.gz  icons
application-9a60f311d75fe590bdfa337903515d6d.css    icons-sae006ecc6a.png
application-9a60f311d75fe590bdfa337903515d6d.css.gz manifest.yml
application.css                     rails-e4b51606cd77fda2615e7439907bfc92.png
application.css.gz                  rails.png
application.js
[sdavis@sdavis:Compass-Issue-625 (master)]$
</pre>

**Comment by aaronchi** [comment]
It seems like the problem was generated here:
https://github.com/chriseppstein/compass/commit/35b9b60c7c0d618c0d21456955cdb7481a49dc8d

This is what is causing the problem:

```
 -      Sass::Engine.new(content_for_images(uri, name, options[:skip_overrides]), sass_options(name, importer, options))
 +      Sass::Engine.new(content_for_images(uri, name, options[:skip_overrides]), sass_options(uri, importer, options))
```

**Comment by scottdavis** [comment]
that was actually a fix for a problem that was causing sass to not return the correct uri to the importer that checks if the sprites needed to be updated I worked with @nex3 to target that problem I think this may have todo with the way the uri is being generated in a windows environment. I found my windows xp cd last night so ill give this a spin this weekend

since you have this open already would you mind print out the uri and pasting it here?

**Comment by scottdavis** [comment]
_note_ it should be the `folder/*.png` if its not thats the issue

**Comment by chriseppstein** [comment]
@charlesr can you help us reproduce this?

**Comment by aaronchi** [comment]
```
uri: icon-16/*.png
name: icon-16
```

for some reason, sending sass_options the uri instead of the name causes the problem on windows

**Comment by scottdavis** [comment]
well that looks correct. maybe theres an issue deeper down in sass?

**Comment by charlesroper** [comment]
Will have a look tomorrow when I'm at the computer.

## 

Sent from the Nexus S.
On Dec 8, 2011 7:15 PM, "Chris Eppstein" <
reply@reply.github.com>
wrote:

**Comment by scottdavis** [comment]
@charlesr any word?

**Comment by charlesroper** [comment]
My apologies. Here's what I see:

```
[C:\Dropbox\Projects\Compass-Issue-625]bundle exec rake assets:precompile
C:/Ruby/Ruby192/bin/ruby.exe C:/Ruby/Ruby192/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
rake aborted!
Invalid argument - C:/Dropbox/Projects/Compass-Issue-625/tmp/sass-cache/c2981f91a199d863bf2d4b5ce2ed08df1f6494bb/*.pngc
  (in C:/Dropbox/Projects/Compass-Issue-625/app/assets/stylesheets/application.css.scss)

Tasks: TOP => assets:precompile:primary
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [C:/Ruby/Ruby192/bin/ruby.exe C:/Ruby/Ruby1...]

Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

[C:\Dropbox\Projects\Compass-Issue-625]ruby -v
ruby 1.9.2p290 (2011-07-09) [i386-mingw32]
```

**Comment by scottdavis** [comment]
={

**Comment by scottdavis** [comment]
can you run with trace?

**Comment by charlesroper** [comment]
https://gist.github.com/1560837

**Comment by chriseppstein** [comment]
This seems to be a sass issue. The filename that sass is selecting for writing the cache file needs to be sanitized/escaped so that it only contains legal characters for windows.

**Comment by chriseppstein** [comment]
I filed a bug there. Closing here.
