### ISSUE TITLE
feature-loaded variable for dependencies.

### ISSUE THREAD

**Issue by scottkellum** [Compass/compass#659]
Add featrue-loaded variables for loading dependencies in add-on frameworks and other compass plugins. For example if border-radius is included then the variable $border-radius-loaded would be true.

``` sass
$border-radius-loaded: false !default
@if $border-radius-loaded
  border-radius(1em)
```

This way stylesheets can gracefully identify missing dependencies, load them if necessary, or compile with or without a fallback.

---

I write a lot of functions in Sass that duplicate features in Compass. For frameworks it would be nice to identify what is loaded in Compass and ignore unnecessary/duplicate code.

**Comment by chriseppstein** [comment]
It's not possible to conditionally import in Sass, so that use case is irrelevant. Somewhat related: There's an open issue to make sass imports a no-op if they've already been imported: https://github.com/nex3/sass/issues/139.

In terms of detecting the existence of a mixin. I think this is better provided as a sass language feature. E.g.:

``` scss
@if mixin-exists(border-radius) { @include border-radius(5px); }
```

**Comment by scottkellum** [comment]
OK, I am adding this variable on all my plugins/files now and it is really helpful. Mixin detection will do the trick as well, although it could be more verbose.

**Comment by chriseppstein** [comment]
what do you mean by "more verbose"?
