### ISSUE TITLE
Creation of px_to_ems SASS function

### ISSUE THREAD

**Issue by richardaday** [Compass/compass#72]
I think compass should include a SASS function that looks like the following:

```
def px_to_ems(pixels, element_font_size_in_px = 18)
  ems_value = !pixels / !element_font_size_in_px
  return ems_value + "em"
end
```

The code above is pseudo code for the SASS function.

This function would be useful when creating websites based in ems.  It would allow you to easily convert px's to ems, and still allow it to be readable when reading the SASS.  For example:

```
!default_font_size = 12px
body
  font-size: px_to_ems(12px, 18px) // returns 1.5em
ul
  font-size: 3ems // equivalent to 36px
  p
    font-size= px_to_ems(18px, 36px) // returns 0.5em
```

Also, we could create a ems_to_px function as well.

**Comment by chriseppstein** [comment]
The conversion between ems and pixels and back is basic division and multiplication. Coupled with Sass's unit handling you can do this:

```
!font_base = 12px / 1em
!large_font_base = 36px / 1em

body
  /* 1.5em
  font-size= 18px / !font_base
ul
  /* 36px
  font-size= 3em * !font_base
  p
    /* 0.5em
    font-size= 18px / !large_font_base
```

Maybe an argument could be made that the function forms are more readable, but they're about the same amount of typing...

**Comment by richardaday** [comment]
I would argue that it's easier to read.  Also, you wouldn't have to think of the math each time (even if it's trivial, you need to stop and make sure you have it right).  Here you just pass in the desired pixels and the parent elements font size.

```
!font_base = 12px / 1em
!large_font_base = 36px / 1em

body
  /* 1.5em
  font-size= px_to_ems(!font_base, 18px)
ul
  /* 36px
  font-size= px_to_ems(36px)
  p
    /* 0.5em
    font-size= px_to_ems(18px, 36px)
```

**Comment by chriseppstein** [comment]
After thinking about this, I believe that simple functions like this are more useful when the user defines it. I don't think there's enough value here to "learn" that this function exists and what it is called. But when you define it yourself, you learn all those things and that makes it much more intuitive to you.

I've filed an [enhancement request](http://github.com/nex3/haml/issues/#issue/73) against sass to make it possible to define sass functions in terms of SassScript instead of just in ruby.
