### ISSUE TITLE
@hide-text optimization

### ISSUE THREAD

**Issue by mathiasschopmans** [Compass/compass#756]
// new technique
.hide-text {
  text-indent: 100%;
  white-space: nowrap;
  overflow: hidden;
}

Pros:
- Really long strings of text will never flow into the container because they always flow away from the container.
- Performance is dramatically improved because a 9999px box is not drawn. Noticeably so in animations on the iPad 1.

see: http://www.zeldman.com/2012/03/01/replacing-the-9999px-hack-new-image-replacement/

**Comment by barraponto** [comment]
I was just about to post this issue. Let's not forget about http://www.stuffandnonsense.co.uk/archives/mir_image_replacement.html and its negative letter-spacing approach. It might be even better since it does not change the box properties at all. However, since it never grew popular, it lacks proper testing for cross browser support. Yet the same is valid for text-indent:  100%;

**Comment by chriseppstein** [comment]
This is in 0.12.
