### ISSUE TITLE
Sticky Footer Clearing

### ISSUE THREAD

**Issue by ckuehne** [Compass/compass#79]
Should not _sticky_footer.sass line 15 be "clear: both" instead of "height= !footer_height"?

**Comment by chriseppstein** [comment]
Maybe you could bring this up on the mailing list. I think it has to be a fixed height with the current implementation.

**Comment by ckuehne** [comment]
" think it has to be a fixed height"
The footer yes (or rather, I guess). The clearing element: no. But it has to contain a "clear: both".

**Comment by chriseppstein** [comment]
Can you either provide supporting documentation or a test case that demonstrates what issue you're having? You're prescribing a fix for an unspecified problem.

**Comment by ckuehne** [comment]
Okay. My fault. The problem occurs only in multicolumn layout. See the troubleshooting  http://ryanfait.com/resources/footer-stick-to-bottom-of-page/. I could imagine others stumbling across this as well. Maybe a "!multicolumn" parameter for the sticky footer mixin or something like that would do the job.

**Comment by avit** [comment]
The #root_footer is not a clearing element. It adds padding to the bottom of the content area (in the top-level "root" or "wrapper" element). The padding size corresponds to the height of the footer, and without its height the footer would intrude into the content area when the content is too long for the window.

Ryan Fait's code calls it .push and the element on his example page isn't set to clear, it only has height.

In principle, I think you're right that this element should usually clear, but that might be a separate concern: I wonder if there's a situation where you wouldn't want it to clear, if the mixin would be overreaching by adding the clear for you?

I guess I haven't run into this problem because my multicolumn layouts don't leave extra room for this element to float into, or else because the columns are protected inside another block element.

**Comment by avit** [comment]
Since clearing seems to be the default case anyway, I think I would be fine with adding it as a default. !no_clear could be an optional last parameter. What do you think?

**Comment by chriseppstein** [comment]
[Compass Core] Clear the sticky footer so that it works correctly with grid layouts. Closed by 6b5ffdb0d68da79e2639cac9f2323d312ba4c867.

**Comment by samgro** [comment]
I don't believe this issue is fixed - if I have floating elements at the end of the root element, they won't clear above the footer. The root-footer element also needs a `clear: both`. I fixed the issue in 7a1e27338f2fecbf5841b1c6776ca1cfb34059ca - I'd be happy to submit an example/test cases/pull request etc. if people think this is worth fixing.
