### ISSUE TITLE
Vertical Rhythm: results seem off

### ISSUE THREAD

**Issue by chrisnicola** [Compass/compass#806]
I've been trying to figure out why vertical rhythm produces spacing that looks wildly off, I'm either using it wrong or the calculations it uses are wrong.

Here's the example:

I'm using all the VR defaults to start. I then go to set a larger size for say H2 like this:

```
h2 { 
  @include adjust-font-size-to(1.5 * $base-font-size);
}
```

Now the result should be a font-size of 1.5em and a line-height of 1em according to every article on vertical rhythm I've read out there (e.g. http://24ways.org/2006/compose-to-a-vertical-rhythm) but instead I get a height of 2em (1.5 if I allow half values).

It seems that these mixins operate under the premise that every distance needs to be a whole multiple of the smallest line height. Except I can't find any description of vertical rhythm that works this way.

**Comment by chriseppstein** [comment]
I think you've misunderstood. If the line height stayed at 1em then the text would overlap vertically when you change the font size to more than a line height. The point of maintaining a vertical rhythm to is to make sure that the vertical rhythm (line heights) of the page is not disrupted by changes to the font size.

If you're ok with the rhythm of the page having "off beats" then you can set [`$round-to-nearest-half-line`](http://compass-style.org/reference/compass/typography/vertical_rhythm/#const-round-to-nearest-half-line) to true and compass will round to the nearest half-line instead of the nearest full line.
