### ISSUE TITLE
Fix and document input-placeholder

### ISSUE THREAD

**Issue by Anahkiasen** [Compass/compass#821]
I was looking for a placeholder mixin, and when I found one I noticed by naming it input-placeholder and getting an error, that Compass was actually already including one.
Why is it not documented ? I think that's a pretty useful mixin now that it's correctly supported on modern browsers.

Just one thing : although it is working, it needed a small fix first, the & before each :: or : are actually not needed and throw an error.

**Comment by mirisuzanne** [comment]
I think the idea behind the "&" was that you are applying the mixin to input elements like so:

```
input
  +input-placeholder
    color: red
```

I would guess that you are getting an error because you aren't applying it to anything? I've seen it done both ways, but I think leaving the "&" in compass gives the most flexibility - allowing you to apply the mixin separately to different inputs.

**Comment by ry5n** [comment]
@ericam Yes, that was the intention.

@Anahkiasen Because this is a pseudo-element, when you write it bare (`::-webkit-input-placeholder`) I believe it’s equivalent to `*::-webkit-input-placeholder` (with the universal selector). So, you could write:

``` scss
* {  
  @include input-placeholder {
    color: #ccc;
  }  
}
```

As for the documentation, the feature is pretty new and isn't in the stable release yet. I’m not 100% sure, but I think the docs should appear on compass-style.org when this feature moves to stable, i.e. probably with Compass 0.13. In the meantime, you can peruse the source on the master branch: [mixin](https://github.com/chriseppstein/compass/blob/master/frameworks/compass/stylesheets/compass/css3/_user-interface.scss) and [basic example usage](https://github.com/chriseppstein/compass/tree/master/doc-src/content/examples/compass/css3/input-placeholder).

[edit for typo]

**Comment by Anahkiasen** [comment]
Didn't think about doing *, because I was actually looking into the Bootstrap mixins checking which one were already in Compass and their input-placeholder was for root placement so I just assumed this one was meant to be too. Problem solved :)
