### ISSUE TITLE
Argument names of sprite-map function have changed in 0.12.1

### ISSUE THREAD

**Issue by meyertee** [Compass/compass#828]
Variable names for controlling sprite specific settings don't work like they used to in 0.12.1 (I upgraded from 0.11.7).
This used to work:

```
$icon-sprites: sprite-map("icon/*.png",
  $position: 0%,
  $spacing: 5px,
  $repeat: no-repeat,
  $cart-spacing: 20px);
```

Now it only works by prefixing the variable name with the sprite-map-name ($icon-cart-spacing instead of $cart-spacing):

```
$icon-sprites: sprite-map("icon/*.png",
  $position: 0%,
  $spacing: 5px,
  $repeat: no-repeat,
  $icon-cart-spacing: 20px);
```

The documentation shows the usage without prefixing:
http://compass-style.org/reference/compass/helpers/sprites/#sprite-map

**Comment by Leolik** [comment]
confirm. 
please change documentation or fix sprite-map function. thanks

**Comment by scottdavis** [comment]
oh lame ill get this fixed not sure how it happened ill look into it tonight

**Comment by jnicol** [comment]
I'm just bumping this issue, because the docs still seem inconsistent with the actual behavior in 0.12.2.

The docs for sprite-map give the example:

```
$new-position: 100%
```

Whereas in my tests the variable name needs to be prefixed with the name of the folder that the icons reside in. In the case of the docs, this would be:

```
$icons-new-position: 100%
```

It's not clear from the previous comments whether the bug is with the docs, or with Compass?

**Comment by piouPiouM** [comment]
Which syntax was finally chosen?

Beta documentation still refers to the syntax `$<sprite>-repeat` while Compass (master branch) expects the new form `$<map>-<sprite>-repeat`.

Thx.

**Comment by ashleahhill** [comment]
Along with no dashes in filenames gotcha from #898, this would be very useful to have correct in the docs.

**Comment by markdavies** [comment]
The documentation is still incorrect for this - I just lost a few hours trying to figure this out ...

**Comment by jbates** [comment]
I just got stuck on this, so updating to help others. I was working with a mixin that called the sprite function directly and I couldn't figure out whether the spacing variable _to affect a whole sprite map_, not just individual sprites (which is all I could find covered in the [Compass docs](http://compass-style.org/reference/compass/helpers/sprites/#sprite-map)), needed to be prefixed. It doesn't, in that particular use. This does work:

```
$icons: sprite-map("icons/*.png", $spacing: 20px);
```

It does not work with $layout: smart (as I understand it, possibly by design).

**Comment by chriseppstein** [comment]
If you pass the argument to the function yourself there is no directory prefix. If you set a global variable to configure that argument it requires the directory prefix.
