### ISSUE TITLE
Mixin automatically being called without @include

### ISSUE THREAD

**Issue by dmauro** [Compass/compass#909]
I'm trying to switch over to using Compass to compile my SASS so that I can take advantage of the sprite sheet functionality, but I'm running into some problems with my existing mixins. My own linear gradient mixin has the following line:

background: linear-gradient($gradients);

And when I try to compile something that uses this, I get the error:

(Line 61 of static/scss/_mixins.scss: At least two color stops are required for a linear-gradient)

It seems that Compass is trying to use it's own linear-gradient mixin, but I'm trying to use the standard CSS linear-gradient function here.

**Comment by dmauro** [comment]
Perhaps related?
https://gist.github.com/1722819

**Comment by scottdavis** [comment]
You will need to switch to use in compass's background image mixins for the gradients or specifically only include the compass partials you want to use

**Comment by dmauro** [comment]
Where can I find more information about restricting which compass partials I'm using? This would be ideal, I would love to only take advantage of the sprite sheet functionality.

**Comment by scottdavis** [comment]
just import the specific ones you need ex:

``` scss
@import "compass/some/compass/feature"
```

**Comment by chriseppstein** [comment]
linear-gradient is a function that compass defines to receive the same syntax as expected in css. If Sass had vararg support then you could pass this variable as an argument list instead of a single argument. This ability is coming in Sass 3.2, until then, you should work around this like:

``` scss
  background: unquote("linear-gradient(#{$gradients})");
```

I am curious to see your code so I can understand this particular use case better.

**Comment by dmauro** [comment]
So here is an example of the code failing:

``` sass
@mixin custom-grad($gradient) {
    background: linear-gradient($gradient);
}

body {
    @include custom-grad((90deg, rgba(#fff, 1) 0%, rgba(#fff, 0) 100%));
}
```

Whereas this compiles just fine:

``` sass
body {
    background:linear-gradient(90deg, rgba(#fff, 1) 0%, rgba(#fff, 0) 100%);
}
```

It seems to be only within a mixin that the Compass linear-gradient function is unwittingly called.

**Comment by chriseppstein** [comment]
But why do you need this mixin instead of using the compass-provided `background` mixin?

**Comment by dmauro** [comment]
I would simply prefer to keep my code base unaltered. I've been using SASS for sometime and would simply like to try out Compass' sprite sheet capabilities rather than changing all of my mixins.

What I'm unclear on though is, is this a bug? Why is Compass' linear gradient function only called if linear-gradient is called inside an existing mixin?

**Comment by chriseppstein** [comment]
Yes, it's a bug. Sort of. Helper functions in sass are globally defined. Sass needs a way for you to pass this variable as arguments instead of a single valued argument. Or, I need to change that function to special case a single list value passed as a single argument. I'd prefer the former as the latter is quite hard to determine.

You can work around this by simply changing your mixin to accept the result of calling the linear-gradient mixin:

``` scss
@mixin custom-grad($gradient) {
    background: $gradient;
}

body {
    @include custom-grad(linear-gradient(90deg, rgba(#fff, 1) 0%, rgba(#fff, 0) 100%));
}
```

**Comment by chriseppstein** [comment]
Also, it's quite unlikely that your gradient mixins are anywhere near as correct or robust as ours. I suggest you stop fighting and learn to love Compass ^_^

**Comment by chriseppstein** [comment]
Closing this, Sass is going to add variable argument calling semantics and that will solve this issue or you can use the workarounds above or you can not use compass.
