### ISSUE TITLE
alternating-rows-and-columns mixing should add odd class & nth-child(2n+1) class.

### ISSUE THREAD

**Issue by linjunpop** [Compass/compass#932]
A fix for the `alternating-rows-and-columns` mixin,
added `odd` class to th & td,
added `nth-child(2n+1)` selector to th & td,
Also fixes #653

**Comment by chriseppstein** [comment]
I really don't like this mixin anymore. Here's why:
1. No matter how you use it, it's got selectors you don't need. The output should be tailored to use either classes or css3 selectors, but not both.
2. And on top of this, if you're using `.odd` and `.even` classes in your markup and these are out of sync with the nth-child selectors, you get unpredictable output.
3. It uses color math instead of color transformations like lighten and darken.

So to be honest, I'd like to deprecate this mixin and add new, betterer solutions from the community. As such, I'm going to reject this change as the cost of communicating it and possibly breaking existing uses is too large.

**Comment by linjunpop** [comment]
@chriseppstein 

This fix is just for add `odd` class to th & td because previous one has an `even` class, but not `odd` class.

I complete agree with your idea. Maybe someone can PR a good solution :smile:
