### ISSUE TITLE
"environment" variable isn't set, when default

### ISSUE THREAD

**Issue by Whissi** [Compass/compass#971]
Hi,

I am expecting that this code in my config.rb should work:

``` ruby
if environment == :production
    puts "Running in production mode..."
elsif environment == :development
    puts "Running in development mode..."
else
    # Should never be called, because "development" is Compass's default environment value
    puts "Running in an unknown mode..."
end
```

When I now call

```
compass compile
```

I would expect an output like

```
[...]
Running in development mode...
```

but currently I am getting

```
[...]
Running in an unknown mode...
```

If I call compass with "-e $mode", for example like

```
compass compile -e development
```

or

```
compass compile -e production
```

everything is working as expected.

I am not a Ruby guy, but it seems like, that compass doesn't set the environment variable to default, when the parameter wasn't set. But this is what I am expecting from a default value.

**Comment by Whissi** [comment]
I am running Compass v0.12.2 on Windows with Ruby v1.9.3p194.

**Comment by vendruscolo** [comment]
I noted the same behaviour on Compass 0.12.1, Ruby 1.9.2p290 (Mac Os 10.6.8).

**Comment by chriseppstein** [comment]
This is, sadly, more complicated than you might expect. You see, the project type is what dictates the default values of most of the project configuration, however since the project type is generally set in the configuration file, this leaves these defaults in a state of limbo during the config file parse time.

However, if the app type is explicitly set on the CLI, we can do a little better so if you want to pass `--app stand_alone` or `--app rails` when invoking the compass CLI, we'll handle this better now.
