### ISSUE TITLE
Warning: Unable to load CarbonCore. FSEvents will be unavailable.

### ISSUE THREAD

**Issue by lwille** [Compass/compass#98]
I'm getting a warning "Warning: Unable to load CarbonCore. FSEvents will be unavailable." when starting compass -w with:
Rails 2.3.5
Gem 1.3.5
ruby 1.8.7 (2010-01-10 patchlevel 249) [i686-darwin10]

What does this warning mean? AFAIK, FSEvents is needed for watching file/folder changes - will Compass still work? CarbonCore.framework is available on my System.

**Comment by ttilley** [comment]
you're probably not using the OSX standard ruby, which includes rubycocoa by default (and is how FSSM hooks into the native filesystem-watching support). You -can- safely ignore this message... it's just a warning to let you know that the watch functionality is falling back to polling. The polling method is slower and will seriously kill your laptop battery power if you're not attached to a power source because it prevents your disks from spinning down (they're constantly being checked for changes).

**Comment by ttilley** [comment]
if you would, please close this ticket in compass and file it on FSSM (ttilley/fssm) as "dude, your warning messages suck". ;)

**Comment by lwille** [comment]
LOL ^^ thanks for the advice.

**Comment by lessallan** [comment]
Same issue here.

ruby 1.8.6 (2007-09-24 patchlevel 111) [i686-darwin9.5.0]
Rails 2.3.5
RubyCocoa is installed

**Comment by bartschuller** [comment]
If you get this with the MacPorts version of ruby, then port installing rb-cocoa solves the problem.

**Comment by migbar** [comment]
ditto ... running Ruby from RVM
